#!/bin/zsh

docker run -d \
           --restart on-failure:3 \
           -e MYSQL_ROOT_PASSWORD=Kerrigan \
           -v hatchery:/var/lib/mysql \
           -e MYSQL_DATABASE=zerglings \
           --name spawning-pool \
           mysql