#!/bin/zsh

docker run -d \
           -t \
           --name Abathur \
           -v ~/:/root \
           -p 3000:3000 \
           python:2-slim
docker exec Abathur python -m pip install --upgrade pip
docker exec Abathur pip install Flask
echo 'from flask import Flask\napp = Flask(__name__)\n@app.route("/")\ndef hello_world():\n\treturn "<h1>Hello, World!</h1>"' > ~/pepega.py
docker exec -e FLASK_APP=/root/pepega.py \
            Abathur \
            flask run --host=0.0.0.0 --port 3000