#!/bin/zsh

docker service create --name orbital-command \
                      -e RABBITMQ_DEFAULT_USER=pepega \
                      -e RABBITMQ_DEFAULT_PASS=agepep \
                      --network overmind \
                      rabbitmq